# Generated by Django 5.2.6 on 2025-09-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente.', max_length=100)),
                ('email', models.EmailField(help_text='Endereço de e-mail.', max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone.', max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do hotel.', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do hotel.')),
                ('endereco', models.CharField(help_text='Endereço completo do hotel.', max_length=255)),
                ('cidade', models.CharField(help_text='Cidade onde o hotel está localizado.', max_length=100)),
                ('estado', models.CharField(help_text='Estado onde o hotel está localizado.', max_length=100)),
                ('pais', models.CharField(help_text='País onde o hotel está localizado.', max_length=100)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotéis',
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número ou identificador do quarto.', max_length=10)),
                ('tipo', models.CharField(choices=[('solteiro', 'Solteiro'), ('casal', 'Casal'), ('suite', 'Suíte'), ('familia', 'Família')], default='casal', help_text='Tipo de quarto.', max_length=20)),
                ('capacidade', models.IntegerField(help_text='Número máximo de hóspedes.')),
                ('preco_por_noite', models.DecimalField(decimal_places=2, help_text='Preço por noite.', max_digits=10)),
                ('disponivel', models.BooleanField(default=True, help_text='Status de disponibilidade.')),
                ('hotel', models.ForeignKey(help_text='Hotel ao qual o quarto pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='reservas.hotel')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'unique_together': {('hotel', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_check_in', models.DateField(help_text='Data de check-in.')),
                ('data_check_out', models.DateField(help_text='Data de check-out.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', help_text='Status da reserva.', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação da reserva.')),
                ('cliente', models.ForeignKey(help_text='Cliente que fez a reserva.', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente')),
                ('quarto', models.ForeignKey(help_text='Quarto reservado.', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
