# Generated by Django 5.2.6 on 2025-09-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagem_principal',
            field=models.ImageField(blank=True, help_text='Imagem principal do hotel.', null=True, upload_to='hoteis_imagens/'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do quarto.', null=True, upload_to='quartos_imagens/'),
        ),
    ]
