# Generated by Django 5.2.6 on 2025-09-08 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_hotel_imagem_principal_quarto_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(help_text='Usuário associado a este proprietário.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='proprietario',
            field=models.ForeignKey(default=1, help_text='Proprietário deste hotel.', on_delete=django.db.models.deletion.CASCADE, related_name='hoteis', to='reservas.proprietario'),
            preserve_default=False,
        ),
    ]
